spring:
  application:
    name: challengeaccepted
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
    hibernate:
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://sql7.freemysqlhosting.net/sql7120716
    username: sql7120716
    password: 7kppfzz3pc
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  context-path: /api

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    com.challengeaccepted: INFO